// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldkjcvuahfyxgnbyitqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxka2pjdnVhaGZ5eGduYnlpdHFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2Mjg1MjQsImV4cCI6MjA3MzIwNDUyNH0.lNKcp3FvFT-zCYrahzS8YPnX3We3FpThPFaCjtKl3Lc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});